name: Deploy site
on:
  schedule:
    - cron: '15,45 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-feedparser

      - name: run scripts
        run: |
          cd ./firefish
          rm -rf firefish.py
          wget https://github.com/Deletecat/firefish-rss-parsing/releases/download/0.6/firefish.py
          python3 firefish.py
          rm -rf firefish.py
      
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}