on:
    push:
        paths:
            - './firefish/updated'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: commit files
              run: |
                git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git config --local user.name "github-actions[bot]"
                git add -A
                git commit -m "Add changes"
                git push
